import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [location, setLocation] = useState('');
  const [data,setData] = useState({});
  const [weather, setWeather] = useState();
  const [errorMessage, setErrorMessage] = useState('');
  // const icon = wInfo.weather[0].icon; 


  var apiKey = "4228ae0adc973a748d5fafcf75fbc73f"
  var lang = "en";
  var units = "metric";
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${location}&units=${units}&appid=${apiKey}&lang=${lang}`
  // const uri = `http://openweathermap.org/img/w/${icon}.png`

  const searchLocation = (event) => {
    if(event.key === "Enter") {
      axios.get(url)
      .then((response)=>{
        console.clear();
        setData(response.data)
        console.log(response.data);
        setWeather(response.data.weather);
        setErrorMessage("")
      }).catch(err => {
        console.log(err);
        setErrorMessage("Please enter another location.")
        setData({})
        setWeather()
      })
      setLocation('')
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.logo}>
          the
          <br />
          weather
          <br />
          channel 
        </div>
       <div className={styles.search}>
       <input 
          value={location}
          onChange={event => setLocation(event.target.value)}
          placeholder="Enter Location"
          onKeyDown={searchLocation}
          type="text"
        />
       </div>
        

        {errorMessage}
        <div className={styles.location}>
          {data.name}
        </div>
        

        {
          weather && weather.map((w, index) => {
            return (
              <div key={index}>
                <div className={styles.row}>
                  <div className={styles.temp}>{data.main.temp.toFixed()}
                  </div>
                  <h2>°C</h2>
                  <div className={styles.feels_box}>
                    <div className={styles.feels}>
                      <p className={styles.bold}>FEELS</p>
                      <p className={styles.bold}>LIKE</p>
                    </div> 
                      <h3>{data.main.feels_like.toFixed()}</h3>
                      <h4>°C</h4>
                  </div>
                </div>
                
                <div className={styles.col}>
                  <div>{w.main}</div>
                  <p>{w.description}</p>

                  <div className={styles.col2}>
                    <p>WIND</p>
                    <div>{data.wind.speed.toFixed()}m/s</div>
                  </div>
                </div>
              </div>
            )
          })
        }

      </main>
    </>
  )
}
